---
# os:
#   editCommand: 'floaterm'

gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - bold
    selectedRangeBgColor:
      - bold

git:
  paging:
    colorArg: always
    pager: delta --dark --syntax-theme='Enki-Tokyo-Night' --paging=never
    # pager: delta --dark --paging=never
